#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#app
app.package.name=AutoHelper
app.version=1.0.9
#为true时捆绑composeApp/bin下的所有文件
app.bind=false

# HTTP代理
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897

# HTTPS代理
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897