#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#app
app.package.name=AutoHelper
app.version=1.10.1
#ä¸ºtrueæ¶æç»composeApp/binä¸çæææä»¶
app.bind=false

# HTTPä»£ç
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897

# HTTPSä»£ç
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897